# Generated by Django 5.0.6 on 2024-06-24 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('nome_usuario', models.TextField()),
                ('cpf', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.TextField()),
                ('tipo_usuario', models.TextField(choices=[(1, 'Usuário Comum'), (2, 'Instituição')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
